### ISSUE TITLE
WAV_AUDIO_DIR not configured

### ISSUE THREAD

**Issue by thdg** [cadia-lvl/LOBE#3]
WAV_AUDIO_DIR is missing from the config.

**Comment by atliSig** [comment]
When migrating LOBE 2.0 I had to do some quick edits in the production environment. An easy fix would be to append add `WAV_AUDIO_DIR = os.path.join(DATA_BASE_DIR, 'wav_audio/')` to `./settings/common.py`.

**Comment by thdg** [comment]
Added it to the code a543fbc52a1b38bcbbb2dd3861a0516c83fb145a.
